name: cindel_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/cindel
  - packages/cindel_annotations
  - packages/cindel_flutter_libs
  - packages/cindel_generator

hooks:
  user_defines:
    cindel:
      build_native_assets: false
