name: cindel_flutter_libs
description: Prebuilt native libraries and Web runtime assets for Flutter apps that use the Cindel local database.
version: 1.0.0
homepage: https://github.com/mainser/cindel
repository: https://github.com/mainser/cindel
issue_tracker: https://github.com/mainser/cindel/issues
documentation: https://github.com/mainser/cindel/tree/main/packages/cindel_flutter_libs#readme
topics:
  - database
  - nosql
  - flutter-plugin
  - ffi
  - native

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

flutter:
  assets:
    - web/cindel_worker.js
    - web/pkg/cindel_native.js
    - web/pkg/cindel_native_bg.wasm
    - web/pkg/cindel_native.d.ts
    - web/pkg/cindel_native_bg.wasm.d.ts

  plugin:
    platforms:
      android:
        package: dev.cindel.cindel_flutter_libs
        pluginClass: CindelFlutterLibsPlugin
      ios:
        pluginClass: CindelFlutterLibsPlugin
      linux:
        pluginClass: CindelFlutterLibsPlugin
      macos:
        pluginClass: CindelFlutterLibsPlugin
      web:
        pluginClass: CindelFlutterLibsWeb
        fileName: cindel_flutter_libs_web.dart
      windows:
        pluginClass: CindelFlutterLibsPlugin
