name: cindel_flutter_libs
description: Prebuilt native runtime libraries for Flutter apps that use the Cindel NoSQL local database.
version: 0.3.1
homepage: https://github.com/mainser/Cindel
repository: https://github.com/mainser/Cindel
issue_tracker: https://github.com/mainser/Cindel/issues
documentation: https://github.com/mainser/Cindel/tree/main/packages/cindel_flutter_libs#readme
topics:
  - database
  - nosql
  - flutter-plugin
  - ffi
  - native

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.cindel.cindel_flutter_libs
        pluginClass: CindelFlutterLibsPlugin
      linux:
        pluginClass: CindelFlutterLibsPlugin
      windows:
        pluginClass: CindelFlutterLibsPlugin
