name: cindel_annotations
description: Public annotations and schema metadata types for the Cindel NoSQL local database.
version: 0.5.3
homepage: https://github.com/mainser/Cindel
repository: https://github.com/mainser/Cindel
issue_tracker: https://github.com/mainser/Cindel/issues
documentation: https://github.com/mainser/Cindel/tree/main/packages/cindel_annotations#readme
topics:
  - database
  - nosql
  - annotations
  - schema

environment:
  sdk: ^3.11.0

resolution: workspace

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
