name: cindel_annotations
description: Public annotations and schema metadata types for the Cindel NoSQL local database.
version: 0.8.0
homepage: https://github.com/mainser/cindel
repository: https://github.com/mainser/cindel
issue_tracker: https://github.com/mainser/cindel/issues
documentation: https://github.com/mainser/cindel/tree/main/packages/cindel_annotations#readme
topics:
  - database
  - nosql
  - annotations
  - schema

environment:
  sdk: ^3.11.0

resolution: workspace

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
